name: check
description: Minimum HTTP CLI.
version: 0.0.4
repository: https://github.com/testainers/check
homepage: https://check.testainers.com

environment:
  sdk: ^3.9.0

dependencies:
  # https://pub.dev/packages/args
  args: ^2.7.0

  # https://pub.dev/packages/http
  http: ^1.6.0

dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^6.0.0

  # https://pub.dev/packages/markdown
  markdown: ^7.3.0

  # https://pub.dev/packages/test
  test: ^1.29.0

  # https://pub.dev/packages/testainers
  testainers: ^0.3.0
